"""Gradient-based quantum optimal control (GRAPE).

We synthesise piecewise-constant control pulses that steer a quantum system from
the identity toward a desired target unitary. The implementation follows the
*Gradient Ascent Pulse Engineering* algorithm of Khaneja et al. (*J. Magn.
Reson.* **172**, 296, 2005), specialised to a small, dependency-light setting so
that it runs anywhere :mod:`numpy`/:mod:`scipy` are available.

The control Hamiltonian at time-step ``k`` is

.. math::

    H_k = H_{\\text{drift}} + \\sum_c u_{k,c}\\, H_c,

and the propagator is the ordered product of step propagators
:math:`U = U_N \\cdots U_1`. We maximise the gate fidelity

.. math::

    F = \\frac{1}{d^2}\\, \\lvert \\operatorname{Tr}[U_{\\text{target}}^{\\dagger} U] \\rvert^2.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from scipy.linalg import expm

from ..linalg import X, Y


@dataclass
class ControlResult:
    """Outcome of a GRAPE optimisation run."""

    controls: np.ndarray  # shape (n_steps, n_controls)
    fidelity: float
    propagator: np.ndarray
    history: list[float] = field(default_factory=list)


def simulate_pulse(
    controls: np.ndarray,
    dt: float,
    control_hamiltonians: list[np.ndarray],
    drift: np.ndarray | None = None,
) -> np.ndarray:
    """Return the total propagator generated by a piecewise-constant pulse."""
    controls = np.atleast_2d(np.asarray(controls, dtype=float))
    dim = control_hamiltonians[0].shape[0]
    if drift is None:
        drift = np.zeros((dim, dim), dtype=complex)
    total = np.eye(dim, dtype=complex)
    for amplitudes in controls:
        hamiltonian = drift.astype(complex).copy()
        for amp, ctrl in zip(amplitudes, control_hamiltonians, strict=False):
            hamiltonian = hamiltonian + amp * ctrl
        total = expm(-1j * hamiltonian * dt) @ total
    return total


def _gate_fidelity(propagator: np.ndarray, target: np.ndarray) -> float:
    dim = target.shape[0]
    overlap = np.trace(target.conj().T @ propagator)
    return float(np.abs(overlap) ** 2 / dim ** 2)


def grape_pulse(
    target: np.ndarray,
    n_steps: int = 20,
    dt: float = 0.1,
    control_hamiltonians: list[np.ndarray] | None = None,
    drift: np.ndarray | None = None,
    learning_rate: float = 1.0,
    iterations: int = 200,
    seed: int | None = 0,
    tol: float = 1e-8,
) -> ControlResult:
    """Optimise a control pulse that approximates ``target``.

    Parameters
    ----------
    target:
        Target unitary (``d x d``).
    n_steps:
        Number of piecewise-constant control intervals.
    dt:
        Duration of each interval.
    control_hamiltonians:
        List of control Hamiltonians. Defaults to single-qubit ``[X, Y]``.
    drift:
        Static drift Hamiltonian; defaults to zero.
    learning_rate:
        Step size for gradient ascent on the control amplitudes.
    iterations:
        Maximum number of optimisation iterations.
    seed:
        Seed for the random initial pulse. ``None`` for non-deterministic.
    tol:
        Early-stopping tolerance on ``1 - fidelity``.

    Returns
    -------
    ControlResult
        Optimised controls, achieved fidelity, propagator, and history.
    """
    target = np.asarray(target, dtype=complex)
    if control_hamiltonians is None:
        control_hamiltonians = [X, Y]
    dim = target.shape[0]
    if drift is None:
        drift = np.zeros((dim, dim), dtype=complex)

    rng = np.random.default_rng(seed)
    n_controls = len(control_hamiltonians)
    controls = 0.1 * rng.standard_normal((n_steps, n_controls))

    history: list[float] = []
    best = ControlResult(controls.copy(), 0.0, np.eye(dim, dtype=complex), history)

    for _ in range(iterations):
        # Forward propagators U_k ... U_1 and step propagators.
        step_props = []
        forward = [np.eye(dim, dtype=complex)]
        for amplitudes in controls:
            hamiltonian = drift.astype(complex).copy()
            for amp, ctrl in zip(amplitudes, control_hamiltonians, strict=False):
                hamiltonian = hamiltonian + amp * ctrl
            step = expm(-1j * hamiltonian * dt)
            step_props.append(step)
            forward.append(step @ forward[-1])
        propagator = forward[-1]

        fidelity = _gate_fidelity(propagator, target)
        history.append(fidelity)
        if fidelity > best.fidelity:
            best = ControlResult(controls.copy(), fidelity, propagator.copy(), history)
        if 1.0 - fidelity < tol:
            break

        # Backward propagators L_k = U_N ... U_{k+1}.
        backward = [np.eye(dim, dtype=complex)]
        for step in reversed(step_props):
            backward.append(backward[-1] @ step)
        backward = backward[::-1]  # backward[k] = U_N ... U_{k+1}

        overlap = np.trace(target.conj().T @ propagator)
        gradient = np.zeros_like(controls)
        for k in range(n_steps):
            u_k = forward[k]          # U_{k-1} ... U_1
            l_k = backward[k + 1]     # U_N ... U_{k+1}
            for c, ctrl in enumerate(control_hamiltonians):
                deriv = l_k @ (-1j * dt * ctrl) @ step_props[k] @ u_k
                grad_overlap = np.trace(target.conj().T @ deriv)
                gradient[k, c] = (2.0 / dim ** 2) * np.real(np.conj(overlap) * grad_overlap)

        controls = controls + learning_rate * gradient

    return best
